- name: "configure {{ component }} server"
  hosts: all
  connection: local
  vars_files:
  - "variables-{{ env }}.yaml" # Here variables-dev/prod.yaml files will be loaded
  become: yes
  roles:
  - "{{ component }}"