- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start and Enable MySQL server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9 # pip3.11 if python version is 3.11

# check password is already setup or not
- name: check DB connection 
  community.mysql.mysql_info: # Using Community Module (Internet)
    login_user: root
    login_password: "{{ mysql_root_password }}" # In vars/ main.yaml
    # This var checks every where like: Play level, task level all.... finally in vars/main.yaml (Founded)
    login_host: "{{ login_host }}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output
# If Above failed --> then it is not setup , else Setup
- name: print output
  ansible.builtin.debug:
    msg: "Output: {{mysql_connection_output}} "

- name: setup root password #No Module to setup, that's why we wrote mannually
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_connection_output.failed is true